import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase environment variables!');
  console.error('Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file');
}

export const supabase = createClient(supabaseUrl || '', supabaseAnonKey || '');

// Database types (will be generated by Supabase)
export interface AdminProfile {
  id: string;
  user_id: string;
  name: string;
  mobile: string;
  shop_name?: string;
  location_lat?: number;
  location_lng?: number;
  location_address?: string;
  location_house_address?: string;
  location_landmark?: string;
  created_at: string;
  updated_at: string;
}

export interface Shipment {
  id: number;
  user_id: string;
  admin_mobile: string;
  admin_lat: number;
  admin_lng: number;
  admin_address?: string;
  admin_house_address?: string;
  admin_landmark?: string;
  customer_name: string;
  customer_mobile: string;
  customer_location_link: string;
  customer_address: string;
  customer_landmark: string;
  price: number;
  status: string;
  accepted_rider_id?: string;
  created_at: string;
  updated_at: string;
}

// Address API
import type { AdminAddress, CreateAddressInput, UpdateAddressInput } from '../types/address';

export const AddressAPI = {
  // Get all addresses for current user
  async getAll(): Promise<AdminAddress[]> {
    const { data, error } = await supabase
      .from('admin_addresses')
      .select('*')
      .order('is_default', { ascending: false })
      .order('created_at', { ascending: false });
    
    if (error) throw error;
    return data || [];
  },

  // Get default address
  async getDefault(): Promise<AdminAddress | null> {
    const { data, error } = await supabase
      .from('admin_addresses')
      .select('*')
      .eq('is_default', true)
      .maybeSingle();
    
    if (error) throw error;
    return data;
  },

  // Get address by ID
  async getById(id: string): Promise<AdminAddress | null> {
    const { data, error } = await supabase
      .from('admin_addresses')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    
    if (error) throw error;
    return data;
  },

  // Create new address
  async create(input: CreateAddressInput): Promise<AdminAddress> {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('Not authenticated');

    const { data, error} = await supabase
      .from('admin_addresses')
      .insert({
        ...input,
        user_id: user.id,
      })
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },

  // Update address
  async update(input: UpdateAddressInput): Promise<AdminAddress> {
    const { id, ...updates } = input;
    
    const { data, error } = await supabase
      .from('admin_addresses')
      .update(updates)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },

  // Delete address
  async delete(id: string): Promise<void> {
    const { error } = await supabase
      .from('admin_addresses')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
  },

  // Set as default
  async setDefault(id: string): Promise<void> {
    const { error } = await supabase
      .from('admin_addresses')
      .update({ is_default: true })
      .eq('id', id);
    
    if (error) throw error;
  },
};

